// Utility functions for generating employee profile downloads

export interface Employee {
  id: number;
  name: string;
  role: string;
  department: string;
  location: string;
  experience: string;
  specialties: string[];
  projects: string[];
  education: string;
  certifications: string[];
  languages: string[];
}

export const generateProfilePDF = (employee: Employee): void => {
  // In a real implementation, this would use a PDF generation library like jsPDF
  // For now, we'll create a simple text-based profile and trigger download
  
  const profileContent = `
EMPLOYEE PROFILE
================

Name: ${employee.name}
Role: ${employee.role}
Department: ${employee.department}
Location: ${employee.location}
Experience: ${employee.experience}

EDUCATION
---------
${employee.education}

CERTIFICATIONS
--------------
${employee.certifications.map(cert => `• ${cert}`).join('\n')}

SPECIALTIES
-----------
${employee.specialties.map(specialty => `• ${specialty}`).join('\n')}

RECENT PROJECTS
---------------
${employee.projects.map(project => `• ${project}`).join('\n')}

LANGUAGES
---------
${employee.languages.map(lang => `• ${lang}`).join('\n')}

---
Generated by Bluebird Team Portfolio System
Contact: info@bluebird.com
  `.trim();

  // Create and download the profile as a text file (in real app, this would be PDF)
  const blob = new Blob([profileContent], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `${employee.name.replace(/\s+/g, '_')}_Profile.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  // Clean up the URL object
  URL.revokeObjectURL(url);
};

export const generateTeamPortfolio = (employees: Employee[]): void => {
  // Generate a comprehensive team portfolio
  const portfolioContent = `
BLUEBIRD TEAM PORTFOLIO
=======================

COMPANY OVERVIEW
----------------
Bluebird is a leading digital agency with expertise across design, development, 
marketing, and project management. Our international team delivers world-class 
solutions to clients across the Middle East, India, and beyond.

TEAM MEMBERS
============

${employees.map(employee => `
${employee.name.toUpperCase()}
${'-'.repeat(employee.name.length)}
Role: ${employee.role}
Department: ${employee.department}
Location: ${employee.location}
Experience: ${employee.experience}

Key Specialties: ${employee.specialties.join(', ')}
Recent Projects: ${employee.projects.slice(0, 3).join(', ')}
Education: ${employee.education}
Languages: ${employee.languages.join(', ')}

`).join('\n')}

CONTACT INFORMATION
-------------------
Email: info@bluebird.com
Website: www.bluebird.com

---
Generated: ${new Date().toLocaleDateString()}
  `.trim();

  const blob = new Blob([portfolioContent], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = 'Bluebird_Team_Portfolio.txt';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  URL.revokeObjectURL(url);
};